apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
  - host: charles.info.example
    http:
      paths:
      - path: /*
        backend:
          serviceName: envoy-proxy
          servicePort: 80